### ISSUE TITLE
Remove upper limit on armadillo dependency

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/ensmallen-feedstock#35]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This package currently has an upper limit on its armadillo dependency of armadillo <10.0a0.  However, based on [this exchange](https://github.com/mlpack/ensmallen/issues/357#issuecomment-1418283315), it seems that this should not be a restriction on this package.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by rcurtin** [comment]
I think with the updated ensmallen packages, this should be solved.  If not please feel free to reopen. :+1:
